# Generated by Django 5.0 on 2023-12-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo_App',
            new_name='Todo_App_Model',
        ),
    ]
